<?php
	echo '
		<option value="Select">Select</option>
		<option value="429">A.P. University of Health Sciences, Vijayawada</option>
		<option value="5">Acharya N G Ranga Agriculture University, Hyderabad</option>
		<option value="349">Acharya Nagarjuna University, Guntur</option>
		<option value="6">Alagappa University , Karaikudi</option>
		<option value="7">Aligarh Muslim University, Aligarh</option>
		<option value="8">Allahabad Agricultural Institute , Allahabad</option>
		<option value="4">Allahabad University, Allahabad</option>
		<option value="9">Amravati University, Amravati</option>
		<option value="10">Andhra University, Visakhapatnam</option>
		<option value="374">Andrews University USA</option>
		<option value="375">Andrews University,USA</option>
		<option value="11">Anna University, Chennai</option>
		<option value="12">Annamalai University, Annamalainagar,</option>
		<option value="13">Arunachal University, Itanagar</option>
		<option value="14">Assam Agricultural University, Jorhat</option>
		<option value="454">Assam Down Town University</option>
		<option value="15">Assam University, Silchar</option>
		<option value="16">Atal Behari Vajpayee Inidian Institute of Informat</option>
		<option value="17">Avinashilingam University for Women, Coimbatore</option>
		<option value="18">Awadhesh Pratap Singh University, Rewa</option>
		<option value="19">B N Mandal University, Madhepura</option>
		<option value="20">Baba Farid University of Health sciences, Faridkot</option>
		<option value="21">Babasaheb Bhimrao Ambedkar Bihar University Muzaff</option>
		<option value="22">Babasaheb Bhimrao Ambedkar University, Lucknow</option>
		<option value="23">Banaras Hindu University, Varanasi</option>
		<option value="24">Banasthali Vidyapeeth, Rajasthan</option>
		<option value="25">Bangalore University, Bangalore</option>
		<option value="26">Barkatullah Vishwavidyalaya, Bhopal</option>
		<option value="27">Bengal Engineering &amp; Science University, Howrah</option>
		<option value="28">Berhampur University, Berhampur</option>
		<option value="29">Bharathiar University, Coimbatore</option>
		<option value="30">Bharathidasan University, Tiruchirappalli</option>
		<option value="31">Bharati Vidyapeeth Deemed University, Pune</option>
		<option value="393">Bharatiya Shiksha Parishad, Uttar Pradesh</option>
		<option value="32">Bhavnagar University, Bhavnagar</option>
		<option value="33">Bidhan Chandra Krishi Viswavidyalaya, Mohunpur, (Di</option>
		<option value="36">Birla Agricultural University, Kanke (Ranchi)</option>
		<option value="35">Birla Institute of Technology and Science, Pilani</option>
		<option value="34">Birla Institute of Technology, Mesra (Ranchi)</option>
		<option value="350">Birsa Agricultural University, Ranchi</option>
		<option value="37">Bundelkhand University, Jhansi</option>
		<option value="38">Burdwan University, Burdwan</option>
		<option value="39">Calcutta  University, Kolkata</option>
		<option value="40">Calicut University, Malappuram Dist</option>
		<option value="451">Calorx Teacher’s University, Ahmadabad</option>
		<option value="384">CBSE Senior School, Delhi.</option>
		<option value="385">CBSE, Delhi</option>
		<option value="41">Central Agricultural University, Imphal</option>
		<option value="42">Central Institute of English &amp; Foreign Languages H</option>
		<option value="43">Central Institute of Fisheries Education,Mumbai</option>
		<option value="44">Central Institute of Higher Tibetan Studies, Varan</option>
		<option value="45">Chandra Shekhar Azad University of Agri &amp; Tech, Kanpur</option>
		<option value="49">Chatrapati Shahu Ji Maharaj University, Kanpur</option>
		<option value="46">Chaudhary Charan Singh Haryana Agricultural University</option>
		<option value="47">Chaudhary Charan Singh University, Meerut</option>
		<option value="48">Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vis</option>
		<option value="405">Chhattisgarh Swami Vivekanand Technical University, Bhilai</option>
		<option value="389">CISE, New Delhi.</option>
		<option value="415">CMJ University, Meghalaya</option>
		<option value="50">Cochin University of science &amp; Technology, Kochi</option>
		<option value="397">Council of Secondary Education Mohali</option>
		<option value="51">Dakshin Bharat Hindi Prachar Sabha, Chennai</option>
		<option value="423">Datta Meghe Institute of Medical Sciences, Nagpur</option>
		<option value="53">Dayalbagh Educational Institute, Agra</option>
		<option value="54">Deccan College Post Graduate &amp; Research Institute</option>
		<option value="55">Deen Dayal Upadhyaya Gorakhpur University, Gorakhp</option>
		<option value="56">Delhi University, Delhi</option>
		<option value="57">Dev Sanskirt Vishwavidyalaya, Hardwar</option>
		<option value="58">Devi Ahilya Vishwavidyalaya, Indore</option>
		<option value="59">Dharamsinh Desai University, Nadiad</option>
		<option value="60">Dibrugarh University, Dibrugarh</option>
		<option value="351">Dr B R Ambedkar National Institute of Tech, Jalandhar</option>
		<option value="61">Dr B R Ambedkar Open University, Hyderabad</option>
		<option value="52">Dr Babasaheb Ambedkar Marathwada University, Aurangabad</option>
		<option value="62">Dr Babasaheb Ambedkar Technological University, Raigad</option>
		<option value="63">Dr Balasaheb Sawant Konkan Krishi Vidyapeeth, Dapoli</option>
		<option value="64">Dr Bhimrao Ambedkar University, Agra </option>
		<option value="352">Dr N T R University of Health Sciences, Vijayawada</option>
		<option value="65">Dr Panjabrao Deshmukh Krishi Vidyapeeth, Akola</option>
		<option value="67">Dr Y S Parmar University of Horticulture  &amp; forest</option>
		<option value="447">Dr. C.V. Raman University, Bilaspur</option>
		<option value="66">Dr. Ram Manohar Lohia Avadh university,Faizabad</option>
		<option value="342">Dr.Babasaheb Ambedkar Open University,Ahmeddabad</option>
		<option value="343">Dr.Harisingh Gour Vishwavidalaya, Sagar.</option>
		<option value="68">Dravidian University, Kuppam</option>
		<option value="419">Eastern Institute for Integrated Learning in Management University, Jorethang</option>
		<option value="69">Fakir Mohan University, Orissa</option>
		<option value="70">Forest Research Institute , Dehradun</option>
		<option value="71">Gandhigram Rural Institute, Gandhigram </option>
		<option value="362">Ganpat University (Notification no.)</option>
		<option value="72">Gauhati University, Guwahati</option>
		<option value="73">Goa University, Goa</option>
		<option value="74">Gokhale Institute of Politics &amp; Economics, Pune</option>
		<option value="427">Gondwana University</option>
		<option value="437">Government Institute of Printing Technology</option>
		<option value="75">Govind Ballabh Pant University  of Agriculture  &amp; </option>
		<option value="416">Govt. Recognised Board / Tech. Board</option>
		<option value="433">Griggs Univesity</option>
		<option value="76">Gujarat Ayurved University,Jamnagar</option>
		<option value="77">Gujarat University, Ahmedabad</option>
		<option value="78">Gujarat Vidyapeeth, Ahmedabad</option>
		<option value="344">Gujrat Agriculture University,Sardar Krushinagar</option>
		<option value="79">Gulbarga University, Gulbarga</option>
		<option value="80">Guru Ghasidas University, Bilaspur</option>
		<option value="81">Guru Gobind Singh Indraprastha University, Delhi</option>
		<option value="82">Guru Jambheshwar University, Hisar</option>
		<option value="84">Guru Nanak Dev University, Amritsar</option>
		<option value="83">Gurukul Kangri Vishwavidyalaya, Hardwar</option>
		<option value="86">Hemchandracharya North Gujarat University, Patan</option>
		<option value="85">Hemwati Nandan Bahuguna Garhwal University, Srinag</option>
		<option value="87">Himachal Pradesh University , Shimla</option>
		<option value="448">Himalayan University, Itanagar</option>
		<option value="382">HSC Board Hariyana</option>
		<option value="309">HSC Board of Ajmer</option>
		<option value="310">HSC Board of Allahabad</option>
		<option value="311">HSC Board of Amravati</option>
		<option value="312">HSC Board of Andhra Pradesh</option>
		<option value="313">HSC Board of Assam</option>
		<option value="314">HSC Board of Aurangabad</option>
		<option value="315">HSC Board of Bhopal</option>
		<option value="316">HSC Board of Bihar</option>
		<option value="317">HSC Board of Chattisgarsh</option>
		<option value="318">HSC Board of Chennai</option>
		<option value="319">HSC Board of Delhi</option>
		<option value="320">HSC Board of Goa</option>
		<option value="321">HSC Board of Guhatti</option>
		<option value="322">HSC Board of Gujrat</option>
		<option value="323">HSC Board of Himachal Pradesh</option>
		<option value="371">HSC Board of Jammu &amp; Kashmir</option>
		<option value="324">HSC Board of Jharkhand</option>
		<option value="325">HSC Board of Karnataka</option>
		<option value="326">HSC Board of Kenya</option>
		<option value="373">HSC Board Of Kerala</option>
		<option value="327">HSC Board of Kolhapur</option>
		<option value="410">HSc Board of Konkan</option>
		<option value="328">HSC Board of Latur</option>
		<option value="431">HSC Board of Madhya Bharat, Gwalior</option>
		<option value="329">HSC Board of Madhya Pradesh</option>
		<option value="330">HSC Board of Manipur</option>
		<option value="414">HSC Board of Meghalaya</option>
		<option value="308">HSC Board of Mumbai</option>
		<option value="331">HSC Board of Nagpur</option>
		<option value="332">HSC Board of Nashik</option>
		<option value="370">HSC Board of Nepal</option>
		<option value="333">HSC Board of Orissa</option>
		<option value="307">HSC Board of Pune</option>
		<option value="334">HSC Board of Raipur</option>
		<option value="336">HSC Board of Sindhudurga (Kudal)</option>
		<option value="337">HSC Board of Solapur</option>
		<option value="338">HSC Board of Tamilnadu</option>
		<option value="339">HSC Board of Thane</option>
		<option value="340">HSC Board of Tripura</option>
		<option value="341">HSC Board of Uttar Pradesh</option>
		<option value="396">HSC Board of Uttarakhand</option>
		<option value="335">HSC Board Rajasthan</option>
		<option value="369">HSC Board, Punjab</option>
		<option value="89">Indian Agricultural Research Institute, New Delhi</option>
		<option value="399">Indian Board of Alternative Medicines, West Bengal.</option>
		<option value="90">Indian Institute of Information Technology, Allaha</option>
		<option value="91">Indian Institute of Science, Bangalore</option>
		<option value="92">Indian Institute of Technology Bombay, Mumbai</option>
		<option value="93">Indian Institute of Technology Delhi, New Delhi</option>
		<option value="94">Indian Institute of Technology Kanpur, Kanpur</option>
		<option value="95">Indian Institute of Technology Kharagpur, Kharagpu</option>
		<option value="96">Indian Institute of Technology Madras, Chennai</option>
		<option value="97">Indian Institute of Technology Roorkee, Roorkee</option>
		<option value="353">Indian Law Institute, New Delhi</option>
		<option value="98">Indian School of Mines Universtiy, Dhanbad</option>
		<option value="99">Indian Statistical Institute, Kolkata</option>
		<option value="100">Indian Veterinary Research Institute, Izatnagar</option>
		<option value="102">Indira Gandhi Agricultural University, Raipur</option>
		<option value="101">Indira Gandhi Institute of Development Research, M</option>
		<option value="103">Indira Gandhi National Open University, New Delhi</option>
		<option value="104">Indira Kala Sangit Vishwavidyalaya, Khairagarh</option>
		<option value="105">Institute  of Advanced Studies in Education, Sarda</option>
		<option value="387">Integral University, Lucknow.</option>
		<option value="106">International  Institute  for Population sciences,</option>
		<option value="345">International Institute of InformationTechnology,Hyderabad</option>
		<option value="435">ITI Bombay</option>
		<option value="107">Jadavpur University, Kolkata</option>
		<option value="354">Jagadguru Ramanandacharya Rajasthan Sanskrit Vishwavidyalaya, Jaipur</option>
		<option value="108">Jagadguru Rambhadracharya Handicapped University, </option>
		<option value="109">Jai Narain Vyas University, Jodhpur</option>
		<option value="110">Jai Prakash Vishwavidyalaya, Chapra</option>
		<option value="111">Jain Vishva Bharati Institute Ladnun</option>
		<option value="404">Jaipur National University,Jaipur</option>
		<option value="346">Jamai Hamdard,New Delhi</option>
		<option value="112">Jamia Milla Islamia New Delhi</option>
		<option value="114">Janardan Rai Nagar Rajasthan Vidyapeeth, Udaipur</option>
		<option value="115">Jawaharlal Nehru Technological University, Hyderab</option>
		<option value="116">Jawaharlal Nehru University, New Delhi</option>
		<option value="117">Jaypee University of Information Technology, Kanda</option>
		<option value="118">Jiwaji University, Gwalior</option>
		<option value="422">Jodhpur National University</option>
		<option value="366">Kachchh   University </option>
		<option value="119">Kakatiya University, Warangal</option>
		<option value="444">Kalinga University, Raipur, Chhattisgarh</option>
		<option value="121">Kameshwar singh Darbhanga Sanskirt University, Dar</option>
		<option value="391">Kamla Nehru Institute Of Technology, Sultanpur. Affiliated to U.P.Technical University.</option>
		<option value="122">Kannada University , Kamalapura (Bellary)</option>
		<option value="123">Kannur University, Kannur</option>
		<option value="376">Kanpur University</option>
		<option value="347">Karnatak University,Dhrawad</option>
		<option value="124">Karnataka State open University, Mysore</option>
		<option value="383">Karnataka State Womens University, Bijapur.</option>
		<option value="277">Kathmandu University, Kathmandu</option>
		<option value="126">Kavikulguru Kalidas Sanskrit Vishwavidyalaya Ramtekam</option>
		<option value="128">Kerala Agricultural University, Thrissur</option>
		<option value="365">Kota University , Kota</option>
		<option value="129">Kumaun University , Nainital</option>
		<option value="130">Kurukshetra University, Kurukshetra</option>
		<option value="131">Kuvempu University, Shankaraghatta (Shimoga distt)</option>
		<option value="132">Lakshmibai National Institute of Physical Educatio</option>
		<option value="133">Lalit Narayan Mithila University, Darbhanga</option>
		<option value="449">M.P. State Open School, Bhopal</option>
		<option value="135">Madhya Pradesh Bhoj (Open) University, Bhopal</option>
		<option value="409">Madhyamik Shiksha Parishad, Delhi</option>
		<option value="137">Madurai Kamaraj University, Madurai</option>
		<option value="138">Magadh University, Bodh Gaya</option>
		<option value="139">Maharaj Sayajirao University of Baroda, Vadodara</option>
		<option value="140">Maharana Pratap University of Agriculture &amp; Techno</option>
		<option value="141">Maharashtra Animal &amp; Fishery Sciences University, </option>
		<option value="395">Maharashtra Council of Indian Medicine, Mumbai.</option>
		<option value="436">Maharashtra Rajya Pariksha Parishad, Pune </option>
		<option value="441">Maharashtra State Board of Vacational Examinations</option>
		<option value="455">Maharashtra University of Health Sciences</option>
		<option value="142">Maharashtra University of Health Sciences Nashik</option>
		<option value="144">Maharshi Dayanand Saraswati University, Ajmer</option>
		<option value="145">Maharshi Dayanand University, Rohtak</option>
		<option value="143">Maharshi Mahesh Yogi Vedic Viswavidyalaya, Jabalpu</option>
		<option value="146">Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalay</option>
		<option value="147">Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalay</option>
		<option value="148">Mahatma Gandhi Kashi Vidyapeeth, Varanasi</option>
		<option value="149">Mahatma Gandhi University, Kottayam</option>
		<option value="150">Mahatma Jyotiba Phule (MJP)Rohilkhand University, </option>
		<option value="151">Mahatma Phule Krishi Vidyapeeth, Rahuri</option>
		<option value="152">Makhanlal Chaturvedi National University of Journalism &amp; Communication, Bhopal</option>
		<option value="153">Malviya National Institute of Technology, Jaipur</option>
		<option value="432">Manav Bharti university.</option>
		<option value="154">Mangalore University, Mangalagangothri</option>
		<option value="155">Manipal University, Manipal</option>
		<option value="156">Manipur University, Imphal</option>
		<option value="157">Manonmaniam Sundaranar University, Tirunelveli</option>
		<option value="158">Marathwada Agricultural University, Parbhani</option>
		<option value="411">MATS  University, Raipur</option>
		<option value="159">Maulana Azad National Institute of Technology, Bho</option>
		<option value="160">Maulana Azad National Urdu University, Hyderabad</option>
		<option value="440">MGM INSTITUTE OF HEALTH SCIENCE, NAVI MUMBAI</option>
		<option value="407">Ministry of Primary, Secondary and Professional Education, Congo</option>
		<option value="161">Mizoram University, Aizwal</option>
		<option value="162">Mohanlal Sukhadia University,Udaypur</option>
		<option value="442">Monad University, NH-24, Delhi-Hapur, Hapur (U.P) </option>
		<option value="163">Mother Terasa Womens University,Kodaikanal</option>
		<option value="434">MSBTE</option>
		<option value="445">Mumbai Hindi Vidyapeeth</option>
		<option value="390">Muzaffarpur Institute Of Technology, Muzaffarpur, Bihar, Reconized by AICTE.</option>
		<option value="166">N T R University of Health Sciences,Vijaywada</option>
		<option value="380">Nagaland Board of School Education,Kohima</option>
		<option value="167">Nagaland University,Kohima</option>
		<option value="168">Nagarjuna University,Nagarjuna Nagar</option>
		<option value="169">Nagpur University, Nagpur</option>
		<option value="170">Nalanda Open University,Patna</option>
		<option value="355">NALSAR University of Law, Hyderabad</option>
		<option value="394">Napier University</option>
		<option value="171">Narendra Deva University of Agriculture &amp; Technolo</option>
		<option value="420">Narsee Monjee Institute of Management Studies, Mumbai</option>
		<option value="172">National Academy of Legal Studies Reaseach Univers</option>
		<option value="173">National Dairy Research Institute,Karnal</option>
		<option value="181">National Iinstitute of Technology Karnatak,Surathk</option>
		<option value="174">National Institute of Mental Health &amp; Neuro scienc</option>
		<option value="381">National Institute of Open Schooling, New Delhi.</option>
		<option value="175">National Institute of Pharmaceutical Education &amp; R</option>
		<option value="180">National Institute of Technology Calicut, Calicut</option>
		<option value="356">National Institute of Technology, Karnataka</option>
		<option value="176">National Institute of Technology, Kurukshetra</option>
		<option value="177">National Institute of Technology,Rourkela</option>
		<option value="178">National Institute of Technology,Silchar</option>
		<option value="179">National Institute of Technology,Warangal</option>
		<option value="182">National Law School of India University, Banglore</option>
		<option value="183">National Law University,Jodhpur</option>
		<option value="184">National Museum Institute of History of Art, conse</option>
		<option value="185">Netaji Subhas Open University,Kolkata</option>
		<option value="186">Nizams Institute of Medical Sciences,Hyderabad</option>
		<option value="189">North Maharashtra University,Jalgaon</option>
		<option value="190">North Orissa University,Baripada</option>
		<option value="188">North-Eastern Hill University,Shilong</option>
		<option value="191">Orissa University  of Agriculture  &amp;  Technology, </option>
		<option value="192">Osmania University,Hyderabad</option>
		<option value="443">Other</option>
		<option value="193">Padmashree Dr.D.Y.Patil Vidyapeeth,Navi Mumbai</option>
		<option value="195">Patna University,Patna</option>
		<option value="196">Periyar University,Salem</option>
		<option value="197">Pondicherry University,Pondicherry</option>
		<option value="198">Postgraduate Institute of Medical Education &amp; Reas</option>
		<option value="199">Potti Sreeramula Telgu University,Hyderabad</option>
		<option value="413">Pravara Rural University</option>
		<option value="412">Prist University</option>
		<option value="200">Pt Ravishankar Shukla University,Raipur</option>
		<option value="1">Pune University</option>
		<option value="202">Punjab Agriculture University,Ludhiana</option>
		<option value="203">Punjab Technical University,Jalandhar</option>
		<option value="194">Punjab University,Chandigarh</option>
		<option value="204">Punjabi University,Patiala</option>
		<option value="205">Rabindra Bharati University,Kolkata</option>
		<option value="207">Rajasthan Agriculture University,Bikaner</option>
		<option value="428">Rajasthan Ayurved University, Jodhpur (Rajasthan)</option>
		<option value="208">Rajasthan Sanskrit Vishwavidalaya,Jaipur</option>
		<option value="401">Rajasthan Technical  University,Kota</option>
		<option value="209">Rajendra Agriculture University,Samastipur</option>
		<option value="211">Rajiv Gandhi Proudyogiki Vishwavidalaya,Bhopal</option>
		<option value="210">Rajiv Gandhi University of Health Sciences,Bangalore</option>
		<option value="357">Rajiv Gandhi University, Itanagar</option>
		<option value="212">Ranchi University,Ranchi</option>
		<option value="417">Rani Channamma University, Belagavi</option>
		<option value="213">Rani Durgavati Vishwavidalaya,Jabalpur</option>
		<option value="358">Rashtrasant Tukadoji Maharaj Nagpur University, Nagpur</option>
		<option value="359">Rashtriya Sanskrit Sansthan, New Delhi</option>
		<option value="214">Rashtriya Sanskrit Vidyapeeth,Tirupati</option>
		<option value="215">Sambalpur University,Sambalpur</option>
		<option value="216">Sampurnanand Sanskrit Vishwavidalaya,Varanasi</option>
		<option value="217">Sanjay Gandhi Postgraduate Institute of Medical sc</option>
		<option value="360">Sant Gadge Baba Amravati University, Amravati</option>
		<option value="218">Sardar Patel University, Vallabh Vidyanagar</option>
		<option value="361">Sardarkrushinagar Dantiwada Agri University, Banaskantha</option>
		<option value="219">Sathyabama University, Chennai</option>
		<option value="220">Saurashtra University,Rajkot</option>
		<option value="221">School of Planning and Architecture,New Delhi</option>
		<option value="222">Shanmugha Arts,Science, Technology and Research Ac</option>
		<option value="223">Sher-e-Kashmir University of Agricultural sciences &amp; Technology Jammu, Jammu</option>
		<option value="224">Sher-e-Kashmir University of Agricultural Sciences &amp; Technology of Kashmir , Srinagar </option>
		<option value="2">Shivaji University, Kolhapur</option>
		<option value="430">Shobhit University , Meerut </option>
		<option value="227">Shreemati Nathibai Damodar Tharkersey Womens University, Mumbai</option>
		<option value="228">Shri Jagannath Sanskrit Vishwavidyalaya,Puri</option>
		<option value="229">Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha , New Delhi.</option>
		<option value="230">Shri Mata Vaishno Devi University, Udhampur</option>
		<option value="424">Shridhar University, Pilani, Rajasthan</option>
		<option value="231">Sido-Kanhu  Murmu University, Dumka</option>
		<option value="232">Sikkim -Manipal University of Health Medical &amp; Technological Sciences, Gangtok</option>
		<option value="364">Solapur University</option>
		<option value="233">South Gujarat University, Surat</option>
		<option value="421">Southern Adventist University</option>
		<option value="453">Spicer Adventist University</option>
		<option value="234">Sree Chitra Tirunal Institute for Medical Sciences &amp; Technology, Thiruvananthapuram</option>
		<option value="235">Sree Sankaracharya University of Sanskrit, Ernakulam</option>
		<option value="236">Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya, Kanchipuram</option>
		<option value="237">Sri Krishnadevaraya University, Anantpur</option>
		<option value="238">Sri Padmavati Mahila Visvavidyalayam, Tirupati,</option>
		<option value="239">Sri Ramchandra University , Chennai</option>
		<option value="240">Sri Sathya Sai Institute of Higher learning, Prasanthinilayam</option>
		<option value="241">Sri Venkateswara Institute of Medical sciences, Tirupati</option>
		<option value="242">Sri Venkateswara University,  Tirupati</option>
		<option value="226">SSC Board  of Kolhapur</option>
		<option value="302">SSC Board of  Rajasthan</option>
		<option value="285">SSC Board of Amravati</option>
		<option value="280">SSC Board of Andhra Pradesh</option>
		<option value="281">SSC Board of Assam</option>
		<option value="286">SSC Board of Aurangabad</option>
		<option value="287">SSC Board of Bhopal</option>
		<option value="284">SSC Board of Bihar</option>
		<option value="288">SSC Board of Delhi</option>
		<option value="289">SSC Board of Goa</option>
		<option value="290">SSC Board of Gujrat</option>
		<option value="282">SSC Board of Harayana</option>
		<option value="398">SSC Board of Himachal Pradesh</option>
		<option value="291">SSC Board of Jammu &amp; Kashmir</option>
		<option value="292">SSC Board of Jharkhand</option>
		<option value="293">SSC Board of Karnataka</option>
		<option value="294">SSC Board of Latur</option>
		<option value="295">SSC Board of Madhya Pradesh</option>
		<option value="296">SSC Board of Manipur</option>
		<option value="283">SSC Board of Mumbai</option>
		<option value="297">SSC Board of Mysore</option>
		<option value="298">SSC Board of Nagpur</option>
		<option value="299">SSC Board of Nashik</option>
		<option value="300">SSC Board of Orissa</option>
		<option value="301">SSC Board of Raipur</option>
		<option value="303">SSC Board of Tamilnadu</option>
		<option value="304">SSC Board of Tripura</option>
		<option value="305">SSC Board of Uttar Pradesh</option>
		<option value="306">SSC Board of West Bengal</option>
		<option value="3">SSC Board Pune</option>
		<option value="386">SSC Board Punjab.</option>
		<option value="378">SSS Board of Kerala</option>
		<option value="244">Swami Ramanand Teerth Marathwada University, Nanded</option>
		<option value="243">Symboisis International University, Pune</option>
		<option value="426">Taekyeung College, Korea</option>
		<option value="247">Tamil Nadu Dr MGR Medical University, Chennai.</option>
		<option value="225">Tamil Nadu Open University, Chennai</option>
		<option value="248">Tamil Nadu Veterinary and Animal sciences University, Chennai</option>
		<option value="249">Tamil University, Thanjavur</option>
		<option value="245">Tamilnadu Agricultural University,Coimbatore</option>
		<option value="250">Tata Institute of Social Sciences. Mumbai</option>
		<option value="452">Telangan State Board of Intermediate Education</option>
		<option value="251">Tezpur University, Tezpur</option>
		<option value="252">Thapar Institute of Engineering and Technology, Patiala</option>
		<option value="425">The ICFAI University, Dehradun</option>
		<option value="368">The Institution of Electronics and Telecommunication Engineers, New Delhi</option>
		<option value="363">The Institution of Engineers (India)</option>
		<option value="438">The Institution of Engineers (India)</option>
		<option value="246">The Tamilnadu Dr Ambedkar Law University, Chennai</option>
		<option value="253">Tilak Maharashtra Vidyapeeth, Pune </option>
		<option value="254">Tilka Manjhi Bhagalpur  University, Bhagalpur</option>
		<option value="388">Tribhuvan University</option>
		<option value="255">Tripura University, Suryamaninagar</option>
		<option value="256">U P Rajarshi  Tandon  Open University, Allhabad</option>
		<option value="406">U.P. Rajarshi Tondon Open University, Alahabad</option>
		<option value="278">University in Mauritius</option>
		<option value="276">University in Nepal </option>
		<option value="257">University of Agricultural  Sciences, Bangalore</option>
		<option value="258">University of Agricultural Sciences, Dharwad</option>
		<option value="348">University of Allahabad, Allahabad</option>
		<option value="367">University of Bikaner, Bikaner</option>
		<option value="372">University Of Cambridge</option>
		<option value="379">University Of Cocody</option>
		<option value="88">University of Hyderabad, Hyderabad</option>
		<option value="113">University of Jammu, Jammu</option>
		<option value="120">University of Kalyani , kalyani</option>
		<option value="125">University of Kashmir, Srinagar</option>
		<option value="127">University of Kerala, Thiruvananthapuram</option>
		<option value="134">University of Lucknow, Lucknow</option>
		<option value="136">University of Madras, Chennai</option>
		<option value="279">University of Mauritius , Mauritius,</option>
		<option value="164">University of Mumbai,Mumbai</option>
		<option value="165">University of Mysore,Mysore</option>
		<option value="187">University of North Bengal,Raja Rammohunpur, (Dist</option>
		<option value="206">University of Rajasthan,Jaipur</option>
		<option value="260">Utkal University of Culture, Bhubaneswar</option>
		<option value="259">Utkal University, Bhubaneswar</option>
		<option value="261">Uttar Pradesh  Technical University, Lucknow</option>
		<option value="418">Uttranchal Shiksha Evam Pariksha Parishad, Ramnagar, Nainital</option>
		<option value="262">V B S  Purvanachal  University, Jaunpur</option>
		<option value="263">Vardhman Mahaveer Open University, Kota</option>
		<option value="264">Veer Kunwar Singh University, Arrah</option>
		<option value="201">Veer Narmad South Gujarat University, Surat</option>
		<option value="265">Vellore Institute of Technology, Vellore</option>
		<option value="266">Vidyasagar University, Midnapore</option>
		<option value="267">Vikram University, Ujjain</option>
		<option value="268">Vinayaka Missions University, Salem</option>
		<option value="269">Vinoba Bhave University, Hazaribaug</option>
		<option value="270">Visva-Bharati, Santiniketan</option>
		<option value="271">Visvesvaraya National Insitute of Technology, Nagpur</option>
		<option value="272">Visveswaraiah Technological University, Belgaum</option>
		<option value="392">West Bengal Council of Higher Secondary Education</option>
		<option value="273">West Bengal University of Animal and Fishery Sciences , Kolkata</option>
		<option value="274">West Bengal University of Technology, Kolkata</option>
		<option value="275">Yashwantrao Chavan Maharashtra Open University, Nashik</option>
	';
	
?>